SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE FILM_GENRES;

TRUNCATE TABLE FRIENDSHIP;

TRUNCATE TABLE FILM_LIKES;

TRUNCATE TABLE MPA_RATINGS;

TRUNCATE TABLE FILM_DIRECTORS;

TRUNCATE TABLE FILMS RESTART IDENTITY;

TRUNCATE TABLE USERS RESTART IDENTITY;

TRUNCATE TABLE GENRE RESTART IDENTITY;

TRUNCATE TABLE FILM_RATING RESTART IDENTITY;

TRUNCATE TABLE DIRECTORS RESTART IDENTITY;

TRUNCATE TABLE REVIEWS RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;

INSERT INTO FILM_RATING (NAME)
VALUES ('G'),                     -- 1
    ('PG'),              -- 2
    ('PG-13'),                   -- 3
    ('R'),  -- 4
    ('NC-17');                     -- 5


INSERT INTO GENRE (NAME)
VALUES ('Комедия'),     -- 1
    ('Драма'),       -- 2
    ('Мультфильм'),    -- 3
    ('Триллер'),    -- 4
    ('Документальный'), -- 5
    ('Боевик');      -- 6
